from Carte import *

places = {  
    "pontAvantDroit":{  "loot":1/2,
                        "pos":[(-7.5*SCALE,5*SCALE),(-6.5*SCALE,5*SCALE),(-8.5*SCALE,5*SCALE),(-5.5*SCALE,5*SCALE),(-9.5*SCALE,5*SCALE),(-4.5*SCALE,5*SCALE)],
                        "func":pontAvantDroit },
    "pontMilieuDroit":{ "loot":1/2,
                        "pos":[(-0.5*SCALE,5*SCALE),(0.5*SCALE,5*SCALE),(-1.5*SCALE,5*SCALE),(1.5*SCALE,5*SCALE),(-2.5*SCALE,5*SCALE),(2.5*SCALE,5*SCALE)],
                        "func":pontMilieuDroit},
    "pontArrDroit":{    "loot":1/2,
                        "pos":[(7.5*SCALE,5*SCALE),(6.5*SCALE,5*SCALE),(8.5*SCALE,5*SCALE),(5.5*SCALE,5*SCALE),(9.5*SCALE,5*SCALE),(4.5*SCALE,5*SCALE)],
                        "func":pontArrDroit},
    "pontAvantGauche":{ "loot":1/2,
                        "pos":[(-7.5*SCALE,-3*SCALE),(-6.5*SCALE,-3*SCALE),(-8.5*SCALE,-3*SCALE),(-5.5*SCALE,-3*SCALE),(-9.5*SCALE,-3*SCALE),(-4.5*SCALE,-3*SCALE)],
                        "func":pontAvantGauche},
    "pontMilieuGauche":{"loot":1/2,
                        "pos":[(-0.5*SCALE,-3*SCALE),(0.5*SCALE,-3*SCALE),(-1.5*SCALE,-3*SCALE),(1.5*SCALE,-3*SCALE),(-2.5*SCALE,-3*SCALE),(2.5*SCALE,-3*SCALE)],
                        "func":pontMilieuGauche},
    "pontArrGauche":{   "loot":1/2,
                        "pos":[(7.5*SCALE,-3*SCALE),(6.5*SCALE,-3*SCALE),(8.5*SCALE,-3*SCALE),(5.5*SCALE,-3*SCALE),(9.5*SCALE,-3*SCALE),(4.5*SCALE,-3*SCALE)],
                        "func":pontArrGauche},
    "moteur":{          "loot":1/2,
                        "pos":[(-9*SCALE,3*SCALE),(-7*SCALE,3*SCALE),(-5*SCALE,3*SCALE),(-7*SCALE,1*SCALE),(-5*SCALE,1*SCALE),(-6*SCALE,2*SCALE)],
                        "func":moteur},
    "cabine":{          "loot":1/2,
                        "pos":[(-7.5*SCALE,-1*SCALE),(-6.5*SCALE,-1*SCALE),(-8.5*SCALE,-1*SCALE),(-5.5*SCALE,-1*SCALE),(-9.5*SCALE,-1*SCALE),(-4.5*SCALE,-1*SCALE)],
                        "func":cabine}, 
    "buffet":{          "loot":1/2,
                        "pos":[(-3*SCALE,0.5*SCALE),(-3*SCALE,1.5*SCALE),(-3*SCALE,-0.5*SCALE),(-3*SCALE,2.5*SCALE),(-3*SCALE,-1.5*SCALE),(-3*SCALE,3.5*SCALE)],
                        "func":buffet},
    "tapis":{           "loot":1/2,
                        "pos":[(-1*SCALE,0.5*SCALE),(-1*SCALE,1.5*SCALE),(-1*SCALE,-0.5*SCALE),(-1*SCALE,2.5*SCALE),(-1*SCALE,-1.5*SCALE),(-1*SCALE,3.5*SCALE)],
                        "func":tapis},
    "tables":{          "loot":1/2,
                        "pos":[(1*SCALE,1*SCALE),(3*SCALE,1*SCALE),(1*SCALE,3*SCALE),(3*SCALE,3*SCALE),(1*SCALE,-1*SCALE),(3*SCALE,-1*SCALE)],
                        "func":tables},
    "pontAvant":{       "loot":1/2,
                        "pos":[(-11*SCALE,1*SCALE),(-11*SCALE,3*SCALE),(-11*SCALE,-1*SCALE),(-13*SCALE,2*SCALE),(-13*SCALE,0),(-15*SCALE,1*SCALE)],
                        "func":pontAvant},
    "pontArriere":{     "loot":1/2,
                        "pos":[(11*SCALE,1*SCALE),(11*SCALE,3*SCALE),(11*SCALE,-1*SCALE),(13*SCALE,2*SCALE),(13*SCALE,0),(15*SCALE,1*SCALE)],
                        "func":pontArriere},
    "chambresGauche":{  "loot":1/2,
                        "pos":[(7.5*SCALE,3*SCALE),(6.5*SCALE,3*SCALE),(8.5*SCALE,3*SCALE),(5.5*SCALE,3*SCALE),(9.5*SCALE,3*SCALE),(4.5*SCALE,3*SCALE)],
                        "func":chambresGauche},
    "chambresDroite":{  "loot":1/2,
                        "pos":[(7.5*SCALE,-1*SCALE),(6.5*SCALE,-1*SCALE),(8.5*SCALE,-1*SCALE),(5.5*SCALE,-1*SCALE),(9.5*SCALE,-1*SCALE),(4.5*SCALE,-1*SCALE)],
                        "func":chambresDroite},
    "salleSecrete":{    "loot":1/2,
                        "pos":[(7.5*SCALE,1*SCALE),(6.5*SCALE,1*SCALE),(8.5*SCALE,1*SCALE),(5.5*SCALE,1*SCALE),(9.5*SCALE,1*SCALE),(4.5*SCALE,1*SCALE)],
                        "func":salleSecrete},
    "bateauDroit":{     "loot":0,
                        "pos":[(),()],
                        "func":bateauDroit},
    "bateauGauche":{    "loot":0,
                        "pos":[(),()],
                        "func":bateauGauche}
}
    